"""initial migration

Revision ID: 0d61c7e4679d
Revises: 
Create Date: 2026-01-15 15:46:48.226788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d61c7e4679d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_mot_de_passe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('utilisee', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_mot_de_passe_id'), 'reset_mot_de_passe', ['id'], unique=False)
    op.create_index(op.f('ix_reset_mot_de_passe_token'), 'reset_mot_de_passe', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_mot_de_passe_token'), table_name='reset_mot_de_passe')
    op.drop_index(op.f('ix_reset_mot_de_passe_id'), table_name='reset_mot_de_passe')
    op.drop_table('reset_mot_de_passe')
    # ### end Alembic commands ###
