"""msg

Revision ID: 14ac774c9631
Revises: e475487ad223
Create Date: 2026-01-29 20:19:02.107783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ac774c9631'
down_revision: Union[str, Sequence[str], None] = 'e475487ad223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandes_stage', sa.Column('encadreur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'demandes_stage', 'encadreurs', ['encadreur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demandes_stage', type_='foreignkey')
    op.drop_column('demandes_stage', 'encadreur_id')
    # ### end Alembic commands ###
