"""msg

Revision ID: 1bbc779c28d7
Revises: 8ca035d86f05
Create Date: 2026-02-08 00:13:23.012818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bbc779c28d7'
down_revision: Union[str, Sequence[str], None] = '8ca035d86f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.add_column('projets', sa.Column('encadreur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projets', 'encadreurs', ['encadreur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projets', type_='foreignkey')
    op.drop_column('projets', 'encadreur_id')
    op.create_table('evaluations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idStage', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', mysql.FLOAT(), nullable=False),
    sa.Column('contenu', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('dateEvaluation', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['idStage'], ['stages.id'], name=op.f('evaluations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    # ### end Alembic commands ###
