"""add collum is active 

Revision ID: 540b1445a40b
Revises: a0faadfd64f5
Create Date: 2026-01-21 21:43:06.984386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540b1445a40b'
down_revision: Union[str, Sequence[str], None] = 'a0faadfd64f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encadreurs', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encadreurs', 'is_active')
    # ### end Alembic commands ###
