"""msg

Revision ID: 80f08d953a16
Revises: de7031e620d6
Create Date: 2026-02-02 12:48:14.806090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80f08d953a16'
down_revision: Union[str, Sequence[str], None] = 'de7031e620d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stagiaires', 'matricule',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
    op.drop_column('stagiaires', 'specialite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stagiaires', sa.Column('specialite', mysql.VARCHAR(length=150), nullable=True))
    op.alter_column('stagiaires', 'matricule',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
