"""Ajout table projet

Revision ID: 85a742a6f0bf
Revises: ba5cab417b41
Create Date: 2026-01-16 10:20:55.323728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a742a6f0bf'
down_revision: Union[str, Sequence[str], None] = 'ba5cab417b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_projet', sa.String(length=50), nullable=False),
    sa.Column('intitule', sa.String(length=200), nullable=False),
    sa.Column('departement', sa.Enum('INFORMATIQUE', 'RH', 'FINANCES', 'EXPLOITATION', 'SUPPORT', 'ADMINISTRATION', name='departementenum'), nullable=False),
    sa.Column('type_stage', sa.Enum('PFE', 'INITIATION', 'PERFECTIONNEMENT', name='typestageenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objectifs', sa.Text(), nullable=True),
    sa.Column('livrables', sa.Text(), nullable=True),
    sa.Column('duree_semaines', sa.Integer(), nullable=True),
    sa.Column('charge_hebdo', sa.Integer(), nullable=True),
    sa.Column('niveau_requis', sa.Enum('LICENCE', 'MASTER', 'DOCTORAT', name='niveauenum'), nullable=True),
    sa.Column('competences', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('complexite', sa.Integer(), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DISPONIBLE', 'AFFECTE', 'TERMINE', name='projetstatusenum'), nullable=True),
    sa.Column('nombre_max_stagiaires', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_projet')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projets')
    # ### end Alembic commands ###
