"""msg

Revision ID: 8ca035d86f05
Revises: f981d02b5c19
Create Date: 2026-02-07 11:10:27.291967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca035d86f05'
down_revision: Union[str, Sequence[str], None] = 'f981d02b5c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('projet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stages', 'projets', ['projet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stages', type_='foreignkey')
    op.drop_column('stages', 'projet_id')
    # ### end Alembic commands ###
