"""add tabele encadrant

Revision ID: a0faadfd64f5
Revises: 85a742a6f0bf
Create Date: 2026-01-21 20:58:27.697544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0faadfd64f5'
down_revision: Union[str, Sequence[str], None] = '85a742a6f0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encadreurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.Enum('junior', 'senior', 'expert', name='gradeenum'), nullable=False),
    sa.Column('departement', sa.Enum('INFORMATIQUE', 'RH', 'FINANCES', 'EXPLOITATION', 'SUPPORT', 'ADMINISTRATION', name='departementenum'), nullable=True),
    sa.Column('actif_encadrement', sa.Boolean(), nullable=False),
    sa.Column('max_stagiaires', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_stagiaires >= 1', name='ck_encadreur_max_stagiaires_positive'),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encadreurs_departement'), 'encadreurs', ['departement'], unique=False)
    op.create_index(op.f('ix_encadreurs_matricule'), 'encadreurs', ['matricule'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encadreurs_matricule'), table_name='encadreurs')
    op.drop_index(op.f('ix_encadreurs_departement'), table_name='encadreurs')
    op.drop_table('encadreurs')
    # ### end Alembic commands ###
