"""msg

Revision ID: ae90cbf5e0cf
Revises: 14ac774c9631
Create Date: 2026-02-02 12:25:47.475524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae90cbf5e0cf'
down_revision: Union[str, Sequence[str], None] = '14ac774c9631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stagiaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Stagiaire', sa.String(length=50), nullable=True),
    sa.Column('type_stage', sa.Enum('PFE', 'INITIATION', 'PERFECTIONNEMENT', name='typestageenum'), nullable=False),
    sa.Column('statut_stage', sa.Enum('EN_COURS', 'TERMINE', 'ANNULE', 'EN_ATTENTE', name='statutstageenum'), nullable=False),
    sa.Column('date_debut_stage', sa.Date(), nullable=False),
    sa.Column('date_fin_stage', sa.Date(), nullable=False),
    sa.Column('structure', sa.String(length=150), nullable=False),
    sa.Column('etablissement', sa.String(length=150), nullable=False),
    sa.Column('niveau_etude', sa.String(length=100), nullable=True),
    sa.Column('specialite', sa.String(length=150), nullable=True),
    sa.Column('encadreur_id', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('note_finale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stagiaires_Stagiaire'), 'stagiaires', ['Stagiaire'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stagiaires_Stagiaire'), table_name='stagiaires')
    op.drop_table('stagiaires')
    # ### end Alembic commands ###
