"""Ajout champs tags, priorite, complexite, nombre_max_stagiaires

Revision ID: ba5cab417b41
Revises: 0d61c7e4679d
Create Date: 2026-01-16 10:18:06.915630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5cab417b41'
down_revision: Union[str, Sequence[str], None] = '0d61c7e4679d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
