"""initial

Revision ID: bd8d829fa2a0
Revises: 4a6f2c1b9d10
Create Date: 2026-04-03 10:57:14.093030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8d829fa2a0'
down_revision: Union[str, Sequence[str], None] = '4a6f2c1b9d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('motDePasse', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ENCADREUR', 'STAGIAIRE', name='roleenum'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('emailVerifie', sa.Boolean(), nullable=True),
    sa.Column('dateCreation', sa.DateTime(), nullable=True),
    sa.Column('dateModification', sa.DateTime(), nullable=True),
    sa.Column('dernierLogin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('encadreurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.Enum('junior', 'senior', 'expert', name='gradeenum'), nullable=False),
    sa.Column('departement', sa.Enum('INFORMATIQUE', 'RH', 'FINANCES', 'EXPLOITATION', 'SUPPORT', 'ADMINISTRATION', name='departementenum'), nullable=True),
    sa.Column('actif_encadrement', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_stagiaires', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_stagiaires >= 1', name='ck_encadreur_max_stagiaires_positive'),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encadreurs_departement'), 'encadreurs', ['departement'], unique=False)
    op.create_index(op.f('ix_encadreurs_matricule'), 'encadreurs', ['matricule'], unique=True)
    op.create_table('messages_internes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_expediteur', sa.Integer(), nullable=False),
    sa.Column('id_destinataire', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=255), nullable=False),
    sa.Column('contenu', sa.String(length=1000), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_destinataire'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['id_expediteur'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_internes_id'), 'messages_internes', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reset_mot_de_passe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('utilisee', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_mot_de_passe_id'), 'reset_mot_de_passe', ['id'], unique=False)
    op.create_index(op.f('ix_reset_mot_de_passe_token'), 'reset_mot_de_passe', ['token'], unique=True)
    op.create_table('demandes_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('etablissement', sa.String(length=200), nullable=False),
    sa.Column('niveau_etude', sa.String(length=100), nullable=False),
    sa.Column('departement_souhaite', sa.String(length=100), nullable=False),
    sa.Column('date_debut_souhaitee', sa.Date(), nullable=False),
    sa.Column('date_fin_souhaitee', sa.Date(), nullable=False),
    sa.Column('competences', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'EN_COURS', 'ACCEPTEE', 'REFUSEE', name='statutdemandeenum'), nullable=False),
    sa.Column('encadreur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_demandes_stage_id'), 'demandes_stage', ['id'], unique=False)
    op.create_table('projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_projet', sa.String(length=50), nullable=False),
    sa.Column('intitule', sa.String(length=200), nullable=False),
    sa.Column('departement', sa.Enum('INFORMATIQUE', 'RH', 'FINANCES', 'EXPLOITATION', 'SUPPORT', 'ADMINISTRATION', name='departementenum'), nullable=False),
    sa.Column('type_stage', sa.Enum('PFE', 'INITIATION', 'PERFECTIONNEMENT', name='typestageenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objectifs', sa.Text(), nullable=True),
    sa.Column('livrables', sa.Text(), nullable=True),
    sa.Column('fiche_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('duree_semaines', sa.Integer(), nullable=True),
    sa.Column('charge_hebdo', sa.Integer(), nullable=True),
    sa.Column('niveau_requis', sa.Enum('LICENCE', 'MASTER', 'DOCTORAT', name='niveauenum'), nullable=True),
    sa.Column('competences', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('complexite', sa.Integer(), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DISPONIBLE', 'AFFECTE', 'TERMINE', name='projetstatusenum'), nullable=True),
    sa.Column('nombre_max_stagiaires', sa.Integer(), nullable=True),
    sa.Column('encadreur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_projet')
    )
    op.create_table('stagiaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=30), nullable=False),
    sa.Column('type_stage', sa.Enum('PFE', 'INITIATION', 'PERFECTIONNEMENT', name='typestageenum'), nullable=False),
    sa.Column('statut_stage', sa.Enum('EN_COURS', 'TERMINE', 'ANNULE', 'EN_ATTENTE', name='statutstageenum'), nullable=False),
    sa.Column('date_debut_stage', sa.Date(), nullable=False),
    sa.Column('date_fin_stage', sa.Date(), nullable=False),
    sa.Column('etablissement', sa.String(length=150), nullable=False),
    sa.Column('niveau_etude', sa.String(length=100), nullable=True),
    sa.Column('encadreur_id', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('note_finale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stagiaires_matricule'), 'stagiaires', ['matricule'], unique=True)
    op.create_table('affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('encadreur_id', sa.Integer(), nullable=False),
    sa.Column('stagiaire_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('AFFECTEE', 'EN_COURS', 'COMPLETEE', 'ANNULEE', name='statutaffectationenum'), nullable=False),
    sa.Column('date_affectation', sa.DateTime(), nullable=False),
    sa.Column('date_debut_prevue', sa.DateTime(), nullable=True),
    sa.Column('date_fin_prevue', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('date_fin_prevue >= date_debut_prevue OR date_debut_prevue IS NULL', name='ck_affectation_dates_valid'),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_stage.id'], ),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affectations_demande_id'), 'affectations', ['demande_id'], unique=False)
    op.create_index(op.f('ix_affectations_encadreur_id'), 'affectations', ['encadreur_id'], unique=False)
    op.create_index(op.f('ix_affectations_id'), 'affectations', ['id'], unique=False)
    op.create_index(op.f('ix_affectations_projet_id'), 'affectations', ['projet_id'], unique=False)
    op.create_index(op.f('ix_affectations_stagiaire_id'), 'affectations', ['stagiaire_id'], unique=False)
    op.create_table('choix_projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('date_choix', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_stage.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_choix_projets_demande_id'), 'choix_projets', ['demande_id'], unique=False)
    op.create_index(op.f('ix_choix_projets_id'), 'choix_projets', ['id'], unique=False)
    op.create_index(op.f('ix_choix_projets_projet_id'), 'choix_projets', ['projet_id'], unique=False)
    op.create_table('demandes_stage_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demandes_stage_status_history_demande_id'), 'demandes_stage_status_history', ['demande_id'], unique=False)
    op.create_index(op.f('ix_demandes_stage_status_history_id'), 'demandes_stage_status_history', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('CV', 'LETTRE', 'CONVOCATION', 'RAPPORT_FINAL', 'ATTESTATION', name='documenttypeenum'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_stage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stagiaire_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('encadreur_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('note >= 0 AND note <= 20', name='ck_evaluations_note_range'),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stagiaire_id', 'projet_id', 'encadreur_id', name='uq_evaluations_stagiaire_projet_encadreur')
    )
    op.create_index(op.f('ix_evaluations_encadreur_id'), 'evaluations', ['encadreur_id'], unique=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_evaluations_projet_id'), 'evaluations', ['projet_id'], unique=False)
    op.create_index(op.f('ix_evaluations_stagiaire_id'), 'evaluations', ['stagiaire_id'], unique=False)
    op.create_table('planning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encadreur_id', sa.Integer(), nullable=False),
    sa.Column('stagiaire_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('MEETING', 'REVIEW', 'VISIT', 'DEADLINE', name='planningeventtypeenum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriorityenum'), nullable=False),
    sa.Column('attendee_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_events_encadreur_id'), 'planning_events', ['encadreur_id'], unique=False)
    op.create_index(op.f('ix_planning_events_id'), 'planning_events', ['id'], unique=False)
    op.create_index(op.f('ix_planning_events_stagiaire_id'), 'planning_events', ['stagiaire_id'], unique=False)
    op.create_index(op.f('ix_planning_events_start_at'), 'planning_events', ['start_at'], unique=False)
    op.create_table('propositions_projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'CHOISI', 'EXPIRE', name='statutpropositionenum'), nullable=False),
    sa.Column('date_choix', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_stage.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propositions_projets_demande_id'), 'propositions_projets', ['demande_id'], unique=False)
    op.create_index(op.f('ix_propositions_projets_id'), 'propositions_projets', ['id'], unique=False)
    op.create_index(op.f('ix_propositions_projets_projet_id'), 'propositions_projets', ['projet_id'], unique=False)
    op.create_index(op.f('ix_propositions_projets_token'), 'propositions_projets', ['token'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demandestage_id', sa.Integer(), nullable=False),
    sa.Column('stagiaire_id', sa.Integer(), nullable=False),
    sa.Column('encadreur_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut_stage', sa.Enum('EN_COURS', 'TERMINE', 'ANNULE', 'EN_ATTENTE', name='statutstageenum'), nullable=False),
    sa.Column('texte_objectif', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['demandestage_id'], ['demandes_stage.id'], ),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    op.create_table('document_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_reviews_document_id'), 'document_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_reviews_id'), 'document_reviews', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'VALIDATED', name='taskstatusenum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriorityenum'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('task_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('stagiaire_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaires.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_submissions_id'), 'task_submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_submissions_id'), table_name='task_submissions')
    op.drop_table('task_submissions')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_document_reviews_id'), table_name='document_reviews')
    op.drop_index(op.f('ix_document_reviews_document_id'), table_name='document_reviews')
    op.drop_table('document_reviews')
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_propositions_projets_token'), table_name='propositions_projets')
    op.drop_index(op.f('ix_propositions_projets_projet_id'), table_name='propositions_projets')
    op.drop_index(op.f('ix_propositions_projets_id'), table_name='propositions_projets')
    op.drop_index(op.f('ix_propositions_projets_demande_id'), table_name='propositions_projets')
    op.drop_table('propositions_projets')
    op.drop_index(op.f('ix_planning_events_start_at'), table_name='planning_events')
    op.drop_index(op.f('ix_planning_events_stagiaire_id'), table_name='planning_events')
    op.drop_index(op.f('ix_planning_events_id'), table_name='planning_events')
    op.drop_index(op.f('ix_planning_events_encadreur_id'), table_name='planning_events')
    op.drop_table('planning_events')
    op.drop_index(op.f('ix_evaluations_stagiaire_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_projet_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_encadreur_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_table('documents')
    op.drop_index(op.f('ix_demandes_stage_status_history_id'), table_name='demandes_stage_status_history')
    op.drop_index(op.f('ix_demandes_stage_status_history_demande_id'), table_name='demandes_stage_status_history')
    op.drop_table('demandes_stage_status_history')
    op.drop_index(op.f('ix_choix_projets_projet_id'), table_name='choix_projets')
    op.drop_index(op.f('ix_choix_projets_id'), table_name='choix_projets')
    op.drop_index(op.f('ix_choix_projets_demande_id'), table_name='choix_projets')
    op.drop_table('choix_projets')
    op.drop_index(op.f('ix_affectations_stagiaire_id'), table_name='affectations')
    op.drop_index(op.f('ix_affectations_projet_id'), table_name='affectations')
    op.drop_index(op.f('ix_affectations_id'), table_name='affectations')
    op.drop_index(op.f('ix_affectations_encadreur_id'), table_name='affectations')
    op.drop_index(op.f('ix_affectations_demande_id'), table_name='affectations')
    op.drop_table('affectations')
    op.drop_index(op.f('ix_stagiaires_matricule'), table_name='stagiaires')
    op.drop_table('stagiaires')
    op.drop_table('projets')
    op.drop_index(op.f('ix_demandes_stage_id'), table_name='demandes_stage')
    op.drop_table('demandes_stage')
    op.drop_index(op.f('ix_reset_mot_de_passe_token'), table_name='reset_mot_de_passe')
    op.drop_index(op.f('ix_reset_mot_de_passe_id'), table_name='reset_mot_de_passe')
    op.drop_table('reset_mot_de_passe')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_internes_id'), table_name='messages_internes')
    op.drop_table('messages_internes')
    op.drop_index(op.f('ix_encadreurs_matricule'), table_name='encadreurs')
    op.drop_index(op.f('ix_encadreurs_departement'), table_name='encadreurs')
    op.drop_table('encadreurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
