"""msg

Revision ID: c6ebf18c15d1
Revises: a612798747d5
Create Date: 2026-02-02 17:33:43.148323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ebf18c15d1'
down_revision: Union[str, Sequence[str], None] = 'a612798747d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demandestage_id', sa.Integer(), nullable=False),
    sa.Column('stagiaire_id', sa.Integer(), nullable=False),
    sa.Column('encadreur_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut_stage', sa.Enum('EN_COURS', 'TERMINE', 'ANNULE', 'EN_ATTENTE', name='statutstageenum'), nullable=False),
    sa.Column('texte_objectif', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['demandestage_id'], ['demandes_stage.id'], ),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_table('stages')
    # ### end Alembic commands ###
