"""msg

Revision ID: de7031e620d6
Revises: ae90cbf5e0cf
Create Date: 2026-02-02 12:34:19.313105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de7031e620d6'
down_revision: Union[str, Sequence[str], None] = 'ae90cbf5e0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stagiaires', sa.Column('matricule', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_stagiaires_Stagiaire'), table_name='stagiaires')
    op.create_index(op.f('ix_stagiaires_matricule'), 'stagiaires', ['matricule'], unique=True)
    op.drop_column('stagiaires', 'structure')
    op.drop_column('stagiaires', 'Stagiaire')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stagiaires', sa.Column('Stagiaire', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('stagiaires', sa.Column('structure', mysql.VARCHAR(length=150), nullable=False))
    op.drop_index(op.f('ix_stagiaires_matricule'), table_name='stagiaires')
    op.create_index(op.f('ix_stagiaires_Stagiaire'), 'stagiaires', ['Stagiaire'], unique=True)
    op.drop_column('stagiaires', 'matricule')
    # ### end Alembic commands ###
