"""ajout_table_propositions_projets

Revision ID: e475487ad223
Revises: 540b1445a40b
Create Date: 2026-01-22 22:11:17.208105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e475487ad223'
down_revision: Union[str, Sequence[str], None] = '540b1445a40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propositions_projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'CHOISI', 'EXPIRE', name='statutpropositionenum'), nullable=False),
    sa.Column('date_choix', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_stage.id'], ),
    sa.ForeignKeyConstraint(['projet_id'], ['projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propositions_projets_demande_id'), 'propositions_projets', ['demande_id'], unique=False)
    op.create_index(op.f('ix_propositions_projets_id'), 'propositions_projets', ['id'], unique=False)
    op.create_index(op.f('ix_propositions_projets_projet_id'), 'propositions_projets', ['projet_id'], unique=False)
    op.create_index(op.f('ix_propositions_projets_token'), 'propositions_projets', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propositions_projets_token'), table_name='propositions_projets')
    op.drop_index(op.f('ix_propositions_projets_projet_id'), table_name='propositions_projets')
    op.drop_index(op.f('ix_propositions_projets_id'), table_name='propositions_projets')
    op.drop_index(op.f('ix_propositions_projets_demande_id'), table_name='propositions_projets')
    op.drop_table('propositions_projets')
    # ### end Alembic commands ###
