"""fix document user relation

Revision ID: e5d0ebf7c072
Revises: 1b31773a9f5c
Create Date: 2026-02-19 17:40:21.242683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5d0ebf7c072'
down_revision: Union[str, Sequence[str], None] = '1b31773a9f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('stagiaire_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stagiaire_id'], ['stagiaires.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_submissions_id'), 'task_submissions', ['id'], unique=False)
    op.add_column('documents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('documents', 'demande_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'documents', 'utilisateurs', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'encadreurs', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'demande_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('documents', 'user_id')
    op.drop_index(op.f('ix_task_submissions_id'), table_name='task_submissions')
    op.drop_table('task_submissions')
    # ### end Alembic commands ###
